/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as NotesListImport } from "./routes/notesList";

// Create/Update Routes

const NotesListRoute = NotesListImport.update({
  path: "/notesList",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/notesList": {
      id: "/notesList";
      path: "/notesList";
      fullPath: "/notesList";
      preLoaderRoute: typeof NotesListImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/notesList": typeof NotesListRoute;
}

export interface FileRoutesByTo {
  "/notesList": typeof NotesListRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/notesList": typeof NotesListRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/notesList";
  fileRoutesByTo: FileRoutesByTo;
  to: "/notesList";
  id: "__root__" | "/notesList";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  NotesListRoute: typeof NotesListRoute;
}

const rootRouteChildren: RootRouteChildren = {
  NotesListRoute: NotesListRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/notesList"
      ]
    },
    "/notesList": {
      "filePath": "notesList.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
